<?php
namespace P4F\Components\Utilities;

use P4F\Components\Utilities\traits\Arrays\ChangeKeyCase as TChangeKeyCase;
use P4F\Components\Utilities\traits\Arrays\Chunk as TChunk;
use P4F\Components\Utilities\traits\Arrays\Column as TColumn;
use P4F\Components\Utilities\traits\Arrays\Combine as TCombine;
use P4F\Components\Utilities\traits\Arrays\Count as TCount;
use P4F\Components\Utilities\traits\Arrays\Diff as TDiff;
use P4F\Components\Utilities\traits\Arrays\Fill as TFill;
use P4F\Components\Utilities\traits\Arrays\Filter as TFilter;
use P4F\Components\Utilities\traits\Arrays\Flip as TFlip;
use P4F\Components\Utilities\traits\Arrays\Intersect as TIntersect;
use P4F\Components\Utilities\traits\Arrays\Key as TKey;
use P4F\Components\Utilities\traits\Arrays\Keys as TKeys;
use P4F\Components\Utilities\traits\Arrays\Map as TMap;
use P4F\Components\Utilities\traits\Arrays\Merge as TMerge;
use P4F\Components\Utilities\traits\Arrays\Pad as TPad;
use P4F\Components\Utilities\traits\Arrays\Pop as TPop;
use P4F\Components\Utilities\traits\Arrays\Product as TProduct;
use P4F\Components\Utilities\traits\Arrays\Push as TPush;
use P4F\Components\Utilities\traits\Arrays\Rand as TRand;
use P4F\Components\Utilities\traits\Arrays\Reduce as TReduce;
use P4F\Components\Utilities\traits\Arrays\Replace as TReplace;
use P4F\Components\Utilities\traits\Arrays\Reverse as TReverse;
use P4F\Components\Utilities\traits\Arrays\Search as TSearch;
use P4F\Components\Utilities\traits\Arrays\Shift as TShift;
use P4F\Components\Utilities\traits\Arrays\Slice as TSlice;
use P4F\Components\Utilities\traits\Arrays\Splice as TSplice;
use P4F\Components\Utilities\traits\Arrays\Sum as TSum;
use P4F\Components\Utilities\traits\Arrays\UDiff as TUDiff;
use P4F\Components\Utilities\traits\Arrays\UIntersect as TUIntersect;
use P4F\Components\Utilities\traits\Arrays\Unique as TUnique;
use P4F\Components\Utilities\traits\Arrays\Unshift as TUnshift;
use P4F\Components\Utilities\traits\Arrays\Values as TValues;
use P4F\Components\Utilities\traits\Arrays\Walk as TWalk;
use P4F\Components\Utilities\traits\Arrays\Compact as TCompact;
use P4F\Components\Utilities\traits\Arrays\Current as TCurrent;
use P4F\Components\Utilities\traits\Arrays\Each as TEach;
use P4F\Components\Utilities\traits\Arrays\End as TEnd;
use P4F\Components\Utilities\traits\Arrays\Extract as TExtract;
use P4F\Components\Utilities\traits\Arrays\InArray as TInArray;
use P4F\Components\Utilities\traits\Arrays\Prev as TPrev;
use P4F\Components\Utilities\traits\Arrays\Next as TNext;
use P4F\Components\Utilities\traits\Arrays\Range as TRange;
use P4F\Components\Utilities\traits\Arrays\Reset as TReset;
use P4F\Components\Utilities\traits\Arrays\Shuffle as TShuffle;
use P4F\Components\Utilities\traits\Arrays\Sort as TSort;
use P4F\Components\Utilities\traits\Arrays\IsArray as TIsArray;
use P4F\Components\Utilities\traits\Arrays\Find as TFind;
use P4F\Components\Utilities\traits\Arrays\First as TFirst;

//todo: (0) kontrola všech array funkcí jestli dělají co mají
class Arrays{
    use TChangeKeyCase;
    use TChunk;
    use TColumn;
    use TCombine;
    use TCount;
    use TDiff;
    use TFill;
    use TFilter;
    use TFlip;
    use TIntersect;
    use TKey;
    use TKeys;
    use TMap;
    use TMerge;
    use TPad;
    use TPop;
    use TProduct;
    use TPush;
    use TRand;
    use TReduce;
    use TReplace;
    use TReverse;
    use TSearch;
    use TShift;
    use TSlice;
    use TSplice;
    use TSum;
    use TUDiff;
    use TUIntersect;
    use TUnique;
    use TUnshift;
    use TValues;
    use TWalk;
    use TCompact;
    use TCurrent;
    use TEach;
    use TEnd;
    use TExtract;
    use TInArray;
    use TPrev;
    use TNext;
    use TRange;
    use TReset;
    use TShuffle;
    use TSort;
    use TIsArray;
    use TFind;
    use TFirst;
}
